server:
  port: 5000
spring:
  config:
    import: optional:classpath:/application-common.properties
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:5001
          predicates:
            - Path=/member/**
        - id: face
          uri: http://127.0.0.1:5010
          predicates:
            - Path=/mface/**
        - id: business
          uri: http://127.0.0.1:5002
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://127.0.0.1:5003
          predicates:
            - Path=/batch/**
      #
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            # 允许携带认证信息
            allow-credentials: true
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowed-origin-patterns:
              - "http://127.0.0.1:5173"
              - "http://127.0.0.1:9000"
              -  "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedMethods: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowedHeaders: "*"